# Generated by Django 3.1.1 on 2020-09-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_phrase', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
                ('romanization', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('word_image', models.ImageField(default='default.jpg', upload_to='word_images')),
            ],
        ),
    ]
